"""assets/audio/timeline.json -> assets/vo-timing.js (word start times keyed 'NN:word')"""
import json, re
from pathlib import Path
root = Path(__file__).resolve().parent.parent
tl = json.loads((root/"assets/audio/timeline.json").read_text())
words, lines = {}, {}
for m in tl:
    n = m["id"][:2]; lines[n] = [m["start"], m["end"]]
    for w in m["words"]:
        k = f'{n}:{re.sub(r"[^a-z0-9]", "", w["text"].lower().replace("’", "").replace(chr(39), ""))}'
        base, i = k, 2
        while k in words: k = f"{base}#{i}"; i += 1
        words[k] = [w["t"], w["te"]]
(root/"assets/vo-timing.js").write_text(
    "// generated by tools/timing_js.py from assets/audio/timeline.json\n"
    f"window.VO_WORDS = {json.dumps(words)};\nwindow.VO_LINES = {json.dumps(lines)};\n")
print(len(words), "words")
